# Input: mcp/scripts/wps-com.ps1 (upstream one-shot COM bridge)
# Output: host/wps-actions.ps1 (dot-sourceable action module exposing Invoke-WpsAction)
# Pos: Reproducible transformation of the one-shot bridge into a resident-host module.
#      Re-run after any upstream re-sync of wps-com.ps1.

param(
    [string]$Source = (Join-Path $PSScriptRoot '..\mcp\scripts\wps-com.ps1'),
    [string]$OutFile = (Join-Path $PSScriptRoot '..\host\wps-actions.ps1')
)

$ErrorActionPreference = 'Stop'

$src = [System.IO.File]::ReadAllText($Source)
# ReadAllText keeps the source BOM as a leading U+FEFF; drop it so we can write exactly one.
$src = $src.TrimStart([char]0xFEFF)

$before = $src
$src = $src -replace '(?s)param\(\s*\[string\]\$Action,\s*\[string\]\$Params\s*=\s*"\{\}"\s*\)', ''
if ($src -eq $before) { throw 'param block not found - upstream layout changed' }

$marker = 'try { $p = $Params | ConvertFrom-Json }'
$idx = $src.IndexOf($marker)
if ($idx -lt 0) { throw 'dispatch boundary not found - upstream layout changed' }
$head = $src.Substring(0, $idx)
$body = $src.Substring($idx)

$beforeHead = $head
$head = $head -replace '(?s)function Output-Json\(\$obj\)\s*\{.*?\}', 'function Output-Json($obj) { $script:WpsResult = $obj }'
if ($head -eq $beforeHead) { throw 'Output-Json not found - upstream layout changed' }

$body = $body -replace '(?m)^\s*exit\s*}\s*$', 'return }'
$body = $body -replace '(?m)^(\s*)exit\s*$', '$1return'
$body = $body -replace '(?m);\s*exit\s*}\s*$', '; return }'
$body = $body -replace '(?m);\s*exit\s*$', '; return'
$body = $body -replace '\{\s*exit\s*\}', '{ return }'

$crlf = [string][char]13 + [string][char]10
$header = '# GENERATED by scripts/build-host-actions.ps1 - do not edit by hand.' + $crlf +
          '# Source: mcp/scripts/wps-com.ps1 (upstream lc2panda/wps-skills).' + $crlf + $crlf
$wrapperOpen = 'function Invoke-WpsAction {' + $crlf + '    param([string]$Action, [string]$Params = ''{}'')' + $crlf + $crlf
$module = $header + $head + $wrapperOpen + $body + $crlf + '}' + $crlf

$enc = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllText($OutFile, $module, $enc)

$bytes = [System.IO.File]::ReadAllBytes($OutFile)
$bom = ($bytes[0..2] | ForEach-Object { $_.ToString('X2') }) -join ' '
$text = [System.IO.File]::ReadAllText($OutFile)
$exitLeft = ([regex]::Matches($text, '\bexit\b')).Count
$cases = ([regex]::Matches($text, '(?m)^\s{4}"[A-Za-z]')).Count
$funcs = ([regex]::Matches($text, '(?m)^function ')).Count
$invoke = ([regex]::Matches($text, 'function Invoke-WpsAction')).Count
$paramsInHead = ([regex]::Matches($head, '\$Action\b|\$Params\b')).Count

'generated: ' + $OutFile
'bytes=' + $bytes.Length + ' bom=' + $bom
'exit_remaining=' + $exitLeft + ' switch_cases=' + $cases + ' functions=' + $funcs + ' invokeDefs=' + $invoke
'head_refs_Action_or_Params=' + $paramsInHead
